name: User Selection Pipeline

on:
  push:
    branches:
      - main

jobs:
  display-file-content:
    runs-on: ubuntu-latest
    outputs:
      file_content: ${{ steps.display-content.outputs.file_content }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display File Content
        id: display-content
        run: |
          cat items.txt  # Update the file path as needed
          echo "{file_content}={$(cat items.txt)}" >> $GITHUB_OUTPUT

  use-selected-item:
    needs: display-file-content
    runs-on: ubuntu-latest
    steps:
      - name: Use Selected Item
        run: |
          file_content="${{ needs.display-file-content.outputs.file_content }}"
          echo "File Content:"
          echo "$file_content"
