name: Read File Content

on:
  push:
    branches:
      - main

jobs:
  read-file-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Read File Content
        id: read-content
        run: |
          file_content=$(cat items.txt)  # Update the file path as needed
          echo "{name}={file_content::$file_content}" >> $GITHUB_OUTPUT

  display-file-content:
    needs: read-file-content
    runs-on: ubuntu-latest
    steps:
      - name: Display File Content
        run: |
          echo "File Content:"
          echo "${{ needs.read-file-content.outputs.file_content }}"
