name: User Selection Pipeline

on:
  push:
    branches:
      - main

jobs:
  display-file-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Files
        run: ls -l

      - name: Display File Content
        id: display-content
        run: |
          cat items.txt  # Update the file path as needed
          echo "Please select an item from the list:"
          read selected_item
          echo "Selected item: $selected_item"

          echo "::set-output name=selected_item::$selected_item"

      - name: Debug Outputs
        run: |
          echo "Debug Outputs:"
          echo "Selected item: ${{ needs.display-content.outputs.selected_item }}"

  use-selected-item:
    needs: display-file-content
    runs-on: ubuntu-latest
    steps:
      - name: Use Selected Item
        run: |
          selected_item="${{ needs.display-file-content.outputs.selected_item }}"
          echo "Selected item: $selected_item"
          # Use the selected item in your next steps or commands
