name: User Selection Pipeline new

on:
  workflow_dispatch:
    inputs:
      env:
        type: string

          
  

jobs:
  display-file-content-test:
    runs-on: ubuntu-latest
    if: ${{  inputs.env == '$test' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: print
        run: |
          test_path=${{ inputs.env }}
          echo "Testing path: $test_path"
          
  display-file-content-test2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: print
        run: |
          test_path=${{ inputs.env }}
          echo "Testing path: $test_path"
