name: User Selection Pipeline new

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        options: 
          - test
          - test2
  

jobs:
  display-file-content:
    runs-on: ubuntu-latest
    if: ${{  inputs.env == 'test' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
